### ISSUE TITLE
Entered numbers with the num pad are jumping around

### ISSUE THREAD

**Issue by rawi96** [brianreavis/selectize.js#1765]
Steps to reproduce:

1. Go to this official Demo: https://selectize.dev/demos/2018/01/02/city-state/
2. Type into the field '999999999...' with the '9' from the numpad (on a big keyboard right)
3. Type into the field '999999999...' with the '9' with the numbers at the top of the keyboard

Expected result:
No difference, no jumping around.

Actual result:
When i type in some '9's from the numpad all the already entered letters are jumping around a little bit.
When i type in some '9's from the top of the keyboad it behaves correctly.

**Comment by risadams** [comment]
I'm not able to check from a PC until early next week, but my first thoughts is that something is happening with the fetch query rather than with input specifically;  i.e. we probably need to debounce the fetch request.  But I'll take a look and confirm as soon as I can.
