### ISSUE TITLE
navigator.userAgent will change in Chrome 101, and currently logs an 'issue' in the console

### ISSUE THREAD

**Issue by mikevaux** [brianreavis/selectize.js#1781]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [ ] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [ ] Indicate *precise* steps to reproduce in *numbers* and the result

---

User Agent strings [are being reduced in Chrome 101](https://blog.chromium.org/2021/05/update-on-user-agent-string-reduction.html). While it looks like the elements Selectize relies on will still be available, it might be best to migrate to `navigator.userAgentData` for safety, and also to avoid an issue being raised in the console every time the library is loaded.

`navigator.userAgentData` is not supported in all browsers, so would need feature detection before ua detection (!) but could be achieved with something along the lines of:

```javascript
function uaDetect(platform, re) {
  if (navigator.userAgentData) {
    return platform === navigator.userAgentData.platform;
  }

  return re.test(navigator.userAgent);
}

var IS_MAC = uaDetect("macOS", /Mac/);
// Unsure of the `platform` which is reported for Android
var SUPPORTS_VALIDITY_API = !uaDetect("[Android Platform]", /android/i) && !!document.createElement('input').validity;
```

Would there be any appetite for this? I can look into the `platform` which is reported for Android devices and create a PR to update both places in the `constants.js` file if so?

Relatedly, does Selectize still need to support IE < 11? It would be quite nice to move these variables to `const`s if not, but `const` [is not supported in IE < 11](https://caniuse.com/?search=const).

**Comment by risadams** [comment]
That looks like a great change to me.  a PR would be appreciated :).

Personally I haven't developed for IE 11 in years, but would need to get community feedback before making that large of a change.

**Comment by mikevaux** [comment]
> That looks like a great change to me. a PR would be appreciated :).

Great! That's fine. I've got a pretty tight project schedule for the next couple of weeks, but I'll do one as soon as I can.

> Personally I haven't developed for IE 11 in years, but would need to get community feedback before making that large of a change.

Ha, me neither 😄 Sure, that's fine 👍
