### ISSUE TITLE
Name conflicts of loadingClass default setting with other libraries

### ISSUE THREAD

**Issue by SigurdJanson** [brianreavis/selectize.js#1788]
Welcome to the Selectize bug tracker. Thank you for taking the time to
make Selectize a better library!

Please keep in mind this repository has an important issue backlog and
that maintainers have limited time to fix issues, triage, and understand
them.

If you've never done so, please read the
[guide to reporting issues](https://github.com/selectize/selectize.js/wiki/Reporting-issues-guide)
in the Wiki to help us better understand your issue.

Place an `x` in the checklist steps (`[ ]` becomes `[x]`) to demonstrate
you have done/verified all the steps you needed to do.

Thank you for reading this! You can now erase everything up to the
following dashes, and then complete what's after.

ISSUES THAT EITHER:

* IGNORE THE ISSUE GUIDELINES
* ERASE THE FOLLOWING TEMPLATE
* DON'T FOLLOW THE PROPER NUMBERED FORMAT FOR STEPS TO REPRODUCE

COULD BE CLOSED.

---

I did:

* [X] Search for if my issue has already been submitted
* [X] Make sure I'm reporting something precise that needs to be fixed
* [X] Give my issue a descriptive and concise title
* [ ] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [ ] Indicate *precise* steps to reproduce in *numbers* and the result, like below

*Sorry, the last that was not possible because it's an Shiny app that's affected. **But I think the problem is obvious.** And easy to fix.*

**Description**

The default setting for the option `loadingClass` is `loading`. It happened to cause name conflicts with other libraries and caused unforeseeable effects because the browser applied some CSS element called `loading` that was totally unrelated to the UI control provided by selectize.js.

**Steps to reproduce:**

See https://stackoverflow.com/questions/71880755/weird-behavior-of-selectizeinput. In other words, if you had an R environment you could simply copy/paste the code of the PO.

Expected result: hopefully, name conflicts in the CSS can be avoided. We could probably just use 'selectize-loading' instead of 'loading'. That would minimise the likelihood of confusion, would it not?

Actual result: in the issue at Stackoverflow the effect is that the control is jumping up and down when re-loading from the server.

**Comment by risadams** [comment]
I generally agree with this, but changing the loading class name here would be a breaking change that my need to wait a bit.
