### ISSUE TITLE
Critical dependency 

### ISSUE THREAD

**Issue by packok40** [brianreavis/selectize.js#1803]
Steps to reproduce:

1. npm i selectize
2. npm installl

Actual result:

npm audit    

                       === npm audit security report ===

                                 Manual Review
             Some vulnerabilities require your attention to resolve

          Visit https://go.npm.me/audit-guide for additional guidance

  Critical        Prototype Pollution in minimist

  Package         minimist

  Patched in      >=1.2.6

  Dependency of   selectize

  Path            selectize > sifter > optimist > minimist

  More info       https://github.com/advisories/GHSA-xvch-5gv4-984h

  Moderate        Prototype Pollution in minimist

  Package         minimist

  Patched in      >=0.2.1

  Dependency of   selectize

  Path            selectize > sifter > optimist > minimist

  More info       https://github.com/advisories/GHSA-vh95-rmgr-6w4m

found 2 vulnerabilities (1 moderate, 1 critical) in 1282 scanned packages
  2 vulnerabilities require manual review. See the full report for details.

please update minimist library...

**Comment by risadams** [comment]
you are installing an out of date version.
change your step 1 to  `npm i @selectize/selectize`

**Comment by packok40** [comment]
@risadams thank you!
