### ISSUE TITLE
Typo in home page

### ISSUE THREAD

**Issue by tuanbht** [brianreavis/selectize.js#1835]
Description
---
- Wrong module name: Missing `e` in there. 
- Correct node module name: `@selectize/selectize`

<img width="1676" alt="Screen Shot 2022-07-23 at 10 20 39" src="https://user-images.githubusercontent.com/56242492/180588705-f7c14cb0-d81e-4e79-bb5c-928bcaf5bb19.png">

**Comment by risadams** [comment]
Typing is clearly my strongest skill 🤪.  Will get it fixed now!
