### ISSUE TITLE
Page jumps to the left when clicking on a .item element

### ISSUE THREAD

**Issue by authyrtyr** [brianreavis/selectize.js#1877]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [ ] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

When you have a selectize dropdown so far to the right that the page has a scrollbar across the bottom, clicking on any of the .item elements in the selectize div causes the page to jump all the way to the left. I tried to create a minimal case on jsfiddle but couldn't get it to run selectize without errors for some reason. [Here's](https://jsfiddle.net/0aLdk56x/) my fiddle for reference but it doesn't quite work. Should at least give an idea of what I mean though. Unfortunately, I don't have the time to spend all day messing with it.

Steps to reproduce:

1. Select an option from the selectize dropdown
2. Click out of the dropdown so that the options don't display.
3. Click on one of the .item elements (the boxes inside the display that show which options have been selected)

Expected result: Nothing

Actual result: Page scrolls all the way to the left.

This came up because in my application I have tied a delete handler for if they click on the items. We have a really wide page, and I noticed this problem when implementing selectize on that page. I tested it in our environment without any handlers or other special stuff, just pure selectize, and still saw the issue. 

The problem seems to be caused by onItemSelect called through watchChildEvent. If I comment out watchChildEvent then the behavior doesn't occur.

It's also worth noting that the issue doesn't occur if the dropdown is visible (hence step 2). If the dropdown content is currently being shown then the issue doesn't occur.

**Comment by fabienwnklr** [comment]
Maybe it's in relation to #1818 ? If it is, it's fixed by myself with [this commit](https://github.com/fabienwnklr/selectize.js/commit/2313fb7c231d583e7ac0287f81c440ebe6ed045b)

**Comment by authyrtyr** [comment]
@fabienwnklr Sorry for the long delay (I've been swamped). If I apply that change it fixes the problem. You linked it as a single commit, is it in the branch? I'm pretty new with open source stuff.

**Comment by fabienwnklr** [comment]
@authyrtyr it's available in [new release](https://github.com/selectize/selectize.js/releases/tag/v0.14.0)
