### ISSUE TITLE
The `getSelection` method overwrites `window.getSelection`

### ISSUE THREAD

**Issue by skerit** [brianreavis/selectize.js#1885]
This problem was already reported in bug  #1569, but it was auto closed.
Maybe a new name should be found for the function, or it should just not pollute the global scope in some way?

**Comment by fabienwnklr** [comment]
Hey, what version of Selectize you use ? Cause it seem fixed https://github.com/selectize/selectize.js/issues/1569#issuecomment-774225187 

example here : https://jsfiddle.net/54nskzcp/2/

**Comment by risadams** [comment]
> Hey, what version of Selectize you use ? Cause it seem fixed [#1569 (comment)](https://github.com/selectize/selectize.js/issues/1569#issuecomment-774225187)
> 
> example here : https://jsfiddle.net/54nskzcp/2/

I am not positive that it was.  I'll take a look at it again tomorrow morning

**Comment by risadams** [comment]
done #1897. This will be fixed when v0.15 is released.
