### ISSUE TITLE
Dropdown now shown in 0.14.0

### ISSUE THREAD

**Issue by martijndwars** [brianreavis/selectize.js#1909]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

When using "multiple" select with "required", when you click on the text field, the drop down does NOT show. I cannot reproduce this in 0.13.6, so this seems to be a regression in 0.14.0.

CodePen using 0.13.6: https://codepen.io/martijndwars/pen/xxzrKVB
CodePen using 0.14.0: https://codepen.io/martijndwars/pen/abKwoZX

Steps to reproduce:

1. Click on the textbox
2. On 0.13.6: observe dropdown
3. On 0.14.0: observe NO dropdown.

Expected result: always show the dropdown

Actual result: no dropdown is shown in 0.14.0

**Comment by s4muel** [comment]
this commit should solve the issue: https://github.com/selectize/selectize.js/commit/0be60364060ce58ec3deee5d1975f3702ee9de07
in the meantime, use the old one (and wait until 0.15 is released), or try using the current master version

here is the updated playground (JSFiddle, sorry, no codepen account): https://jsfiddle.net/2bck95tz/
i used the dist js from here: https://github.com/selectize/selectize.js/tree/master/dist/js

**Comment by martijndwars** [comment]
Perfect, thanks for answering so quickly! I'll go ahead and close this issue then.

**Comment by martijndwars** [comment]
For anyone finding this issue, version 0.15.0 was released 3 days ago: https://github.com/selectize/selectize.js/releases/tag/v0.15.0
