### ISSUE TITLE
Installation & Usage section on web is out of date: ref to standalone

### ISSUE THREAD

**Issue by spacekpe** [brianreavis/selectize.js#1914]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

Selectize homepage https://selectize.dev/docs.html#installation says:
> All pre-built files needed to use Selectize can be found in the dist folder.
If you're looking to get started with minimal fuss, include standalone/selectize.min.js (bundles Sifter and Microplugin dependencies).

Per https://github.com/selectize/selectize.js/blob/e3d76fc392a752e2121a6bd842a5f8e2249406b8/CHANGELOG.md#v0150--14-11-2022, there is no "standalone" version anymore.

Steps to reproduce:

1. Open webpage https://selectize.dev/docs.html#installation
2. Read it :trollface: 
3. Try to find standalone version

Expected result:
Instructions on the web page can be followed

Actual result:
File referenced on the web page does not exist anymore.

I have to say I feel a bit silly following this issue template :-)

**Comment by spacekpe** [comment]
Oh,  I just noticed that the very same paragraph references MicroPlugin and Sifter which are no more a depedency per
https://github.com/selectize/selectize.js/blob/master/CHANGELOG.md#v0140--02-10-2022

**Comment by risadams** [comment]
TY :)  the docs are super out of date and in desperate need of a rewrite.  it's next on the list.thius this is fixed and updated

**Comment by spacekpe** [comment]
That's impressive speed! Thank you!
