### ISSUE TITLE
Clicking an option after scrolling down the dropdown ends up picking a different option.

### ISSUE THREAD

**Issue by YoYuUm** [brianreavis/selectize.js#1939]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

The proposed fix #1937 has introduced a different bug:

https://user-images.githubusercontent.com/2705679/208436990-0c6573a7-6171-40d5-9f1c-ed7090ea97e8.mov

Steps to reproduce:

(you need to use last dist in repo in order to reproduce this bug)

1. Open a select with many options so it is scrollable.
2. Scroll down the select options and pick one option.
3. A different option (or no option) gets picked.

Expected result:

Should pick the correct option

Actual result:

Picks a wrong option. 

This is most likely happening because in #1937 fix I proposed to focus again the input after it was blurred and the blurred event was ignored. That was helping fixing up another issue described as second example in #1926 . The problem with that fix is that the onBlur call happens on `mousedown` event, that triggers `self.focus()` which makes the options dropdown to scroll to the top, so when `mouseup` event happens, the selected option now is different to the "clicked" option.

I'm not so sure of what the next steps could be, but maybe it would be good to revert #1937 and find a better fix for #1926.

**Comment by risadams** [comment]
Reverted.  I will reopen #1926.  Thanks
