### ISSUE TITLE
lost data() value after selectize()

### ISSUE THREAD

**Issue by twu2** [brianreavis/selectize.js#1958]
in 0.14.0 or old version, the value assign by data() will keep after call selectize().
for example: https://jsfiddle.net/2ju13noh/

in 0.15.0 or new version, the value assign by data() will be 'undefined' after call selectize().
for example: https://jsfiddle.net/uhf960yc/1/

**Comment by twu2** [comment]
It also lost the event trigger we assigned.
0.15.0: https://jsfiddle.net/b3uq6s7c/
0.14.0: https://jsfiddle.net/rjqew25m/

**Comment by twu2** [comment]
revert this will fix this issue: https://github.com/selectize/selectize.js/commit/d2564a0a9f870e3ee53e9306436907a5df0615b6

**Comment by mflorea** [comment]
Regression introduced 4 month ago by https://github.com/selectize/selectize.js/commit/d2564a0a9f870e3ee53e9306436907a5df0615b6#diff-42f49af8bfaecef45ea594811f65dcb9aade0fbd8d3e7246d50ee92e863297caR246 and still present on master.
