### ISSUE TITLE
Can we set empty option to something different than empty string ?

### ISSUE THREAD

**Issue by heyyo-droid** [brianreavis/selectize.js#1959]
In my cms, empty option could be different than '', sometime it's '_none' sometime 'All.
The clear plugins seems to use empty string. Can we change this behavior ?

**Comment by fabienwnklr** [comment]
i'm not sure to understand but, i think this can be help you ? option `emptyOptionLabel` 

you can check all available options here https://selectize.dev/docs/usage#configuration

**Comment by heyyoyo** [comment]
I saw this option, but it doesn't help, this only change the label of the empty option, what I need   to change it's the value of it.
The clear plugin consider it's empty string, I need this value to be configurable

**Comment by fabienwnklr** [comment]
Hmmm okay i see, so i guess you can make a PR for add option `emptyOptionValue` (default is empty)

Tips: provide for the case where value contain undesirable caracters like single or double quotes or other

cf : https://github.com/selectize/selectize.js/blob/master/src/selectize.jquery.js#L158
