### ISSUE TITLE
Selectize drop-down search field

### ISSUE THREAD

**Issue by woodholly** [brianreavis/selectize.js#1960]
My experience showed that search inside "select html element" is non-intuitive for users.
Users keep asking me how to search options inside select field (selectized).
I already added title to selectize field "You can search here, just enter text here", but this is just a workaround.

How to make search field appear inside drop-down list in a place of the first option ? This would be much more intuitive and I can make it look like this:

Closed:
[selectize V]

Opened:
[selectize]
Search: [____________]
option1
option2
...

**Comment by fabienwnklr** [comment]
i think it's currently not possible. But must be good as option / plugin.. maybe an option like `searchPosition: 'input|dropdown' ? I don't know just an idea.. but the idea is good.

i ping @risadams to debate

**Comment by eduardo-mior** [comment]
@fabienwnklr if I'm not mistaken he wants Selectize to work the same as Select2.

When you click on the input, a dropdown opens, inside that dropdown there is a search input.

I particularly think it's much more done, I much prefer the way Selectize works. My users understand selectize perfectly. This is my opinion and my point of view from 1000+ users.

![image](https://user-images.githubusercontent.com/32434418/220326506-27e4467e-b32e-4f50-b35e-7c9a26df4b33.png)

**Comment by fabienwnklr** [comment]
> @fabienwnklr if I'm not mistaken he wants Selectize to work the same as Select2.
> 
> 
> 
> When you click on the input, a dropdown opens, inside that dropdown there is a search input.
> 
> 
> 
> I particularly think it's much more done, I much prefer the way Selectize works. My users understand selectize perfectly. This is my opinion and my point of view from 1000+ users.
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/32434418/220326506-27e4467e-b32e-4f50-b35e-7c9a26df4b33.png)
> 
> 

sure, i agree, that why i propose as an option
