### ISSUE TITLE
Select loses change trigger

### ISSUE THREAD

**Issue by whitsey** [brianreavis/selectize.js#1969]
Change trigger is no longer triggering.  I have a DataTable using selectize v0.12.4 which is working fine (see example: https://live.datatables.net/bixuqage/2/) However, when I update the selectize js to the latest version: v0.15.2 the select no longer triggers the change event and therefore my table does not filter as expected.

Steps to reproduce:

1. Go to example: https://live.datatables.net/bixuqage/2/ - view working change event using v0.12.4 However, on remove the default placeholder is not restored
2. Go to example: https://live.datatables.net/fiyoricu/2/ - view broken selectize change event using v0.15.2 However , on remove the default placeholder IS restored as expected

Expected result:

Selected object should filter the table

Actual result:

Filter is not applying because change evert is not triggered

I actually updated from v0.12.4 because this version was not restoring the default placeholder when all items were deleted from selection. So both versions are buggy. It appears to have changed after v0.14.0

**Comment by artlevitan** [comment]
This is a problem in the incorrect input type and event type.

1. **Change** this in the code https://github.com/selectize/selectize.js/blob/master/src/selectize.js#L138
```javascript
$wrapper = $('<div>').addClass(settings.wrapperClass).addClass(classes + ' selectize-control').addClass(inputMode);
$control = $('<div>').addClass(settings.inputClass + noArrowClass + ' selectize-input items').appendTo($wrapper);
$control_input = $('<input type="text" autocomplete="new-password" autofill="no" />').appendTo($control).attr('tabindex', $input.is(':disabled') ? '-1' : self.tabIndex);
$dropdown_parent = $(settings.dropdownParent || $wrapper);
$dropdown = $('<div>').addClass(settings.dropdownClass).addClass(inputMode + ' selectize-dropdown').hide().appendTo($dropdown_parent);
$dropdown_content = $('<div>').addClass(settings.dropdownContentClass + ' selectize-dropdown-content').attr('tabindex', '-1').appendTo($dropdown);
```

2. on this
```javascript
$wrapper = $('<div>').addClass(settings.wrapperClass).addClass(classes + ' selectize-control').addClass(inputMode);
$control = $('<div>').addClass(settings.inputClass + ' selectize-input items').appendTo($wrapper);
$control_input = $('<input type="text" autocomplete="off">').appendTo($control).attr('tabindex', $input.is(':disabled') ? '-1' : self.tabIndex);
$dropdown_parent = $(settings.dropdownParent || $wrapper);
$dropdown = $('<div>').addClass(settings.dropdownClass).addClass(inputMode + ' selectize-dropdown').hide().appendTo($dropdown_parent);
$dropdown_content = $('<div>').addClass(settings.dropdownContentClass + ' selectize-dropdown-content').attr('tabindex', '-1').appendTo($dropdown);
```

3. And this https://github.com/selectize/selectize.js/blob/master/src/selectize.js#L202
```javascript
$dropdown.on('mouseenter mousedown mouseup click', '[data-disabled]>[data-selectable]', function(e) { e.stopImmediatePropagation(); });
$dropdown.on('mouseenter', '[data-selectable]', function() { return self.onOptionHover.apply(self, arguments); });
$dropdown.on('mouseup click', '[data-selectable]', function() { return self.onOptionSelect.apply(self, arguments); });
watchChildEvent($control, 'mouseup', '*:not(input)', function() { return self.onItemSelect.apply(self, arguments); });
autoGrow($control_input);
```

4. on this
```javascript
$dropdown.on('mouseenter mousedown click', '[data-disabled]>[data-selectable]', function (e) { e.stopImmediatePropagation(); });
$dropdown.on('mouseenter', '[data-selectable]', function () { return self.onOptionHover.apply(self, arguments); });
$dropdown.on('mousedown click', '[data-selectable]', function () { return self.onOptionSelect.apply(self, arguments); });
watchChildEvent($control, 'mousedown', '*:not(input)', function () { return self.onItemSelect.apply(self, arguments); });
autoGrow($control_input);
```

**Comment by mflorea** [comment]
Regression introduced 4 months ago by https://github.com/selectize/selectize.js/commit/d2564a0a9f870e3ee53e9306436907a5df0615b6#diff-42f49af8bfaecef45ea594811f65dcb9aade0fbd8d3e7246d50ee92e863297caR246 and still present on master.

**Comment by simonc** [comment]
Hi there. I can confirm this is indeed a breaking change. Binding the `change` event on `<select>` before selectize is activated on it used to work but doesn't anymore, only events bound afterward or delegated ones work.

**Comment by DanielInvitado** [comment]
> Hi there. I can confirm this is indeed a breaking change. Binding the `change` event on `<select>` before selectize is activated on it used to work but doesn't anymore, only events bound afterward or delegated ones work.

This is indeed the only solution at this moment, set the binding before setting any .on() event function. It would be great if this issue could be solved. It seems that all events are lost after the cloning/binding.
