### ISSUE TITLE
Selectize.dev Homepage: Wrong Example in Plugins-category

### ISSUE THREAD

**Issue by AEckner** [brianreavis/selectize.js#1983]
Hi there!

On the webpage
**https://selectize.dev/docs/plugins/select-on-focus**
the Javascript-code example is that of the previous plugin, not the current one.
So it reads
`plugins: ["restore_on_backspace"]`
at the moment, although it should be something like
`plugins: ["select_on_focus"]`

In addition to this I do not know if the live-example above that is working correctly,
because I can't see what it's supposed to do from the title alone.
But it seems to be broken - when I focus on any given option, that option is not automatically selected.

Kind regards,
Andre

**Comment by AndreEckner** [comment]
bump

**Comment by AndreEckner** [comment]
bump

**Comment by AndreEckner** [comment]
bump

**Comment by eduardo-mior** [comment]
+1

**Comment by AndreEckner** [comment]
bump bump
