### ISSUE TITLE
Event listeners bound to the original element are removed since d2564a0

### ISSUE THREAD

**Issue by xhaggi** [brianreavis/selectize.js#1986]
@risadams the changes introduced in d2564a0 (see below) remove all event listeners bound to the original element. Therefore, you cannot use Selectize in the current version (>= v0.15.x) with jQuery QueryBuilder (https://querybuilder.js.org/) because it relies on a "change" event bound to the original element.

https://github.com/selectize/selectize.js/commit/d2564a0a9f870e3ee53e9306436907a5df0615b6#diff-c68ad915e858debb7d6d31e47fd5259ef9d7f578f6f67bf044c315a0ac2c2370R1405-R1406
```js
$input.replaceWith(inputPlaceholder);
inputPlaceholder.replaceWith($input);
```

https://api.jquery.com/replacewith/
>The .replaceWith() method removes all data and event handlers associated with the removed nodes.

**Steps to reproduce**
https://jsfiddle.net/yxpj6kd8/4/

**Comment by rnbw-spctrm** [comment]
I am also running into this. There are several other change events that need to remain after selectize is initialized. Considering there seems to be no way to store the element's events, initialize selectize, and then reapply them, this is a breaking change that is preventing me from updating.

**Comment by chalda-pnuzig** [comment]
I have the same issue...
I attempted to update selectize to the latest version, but after the update, all the events that were present on the select before initialization are erased.
It would be great to have an option to prevent this behavior.
