### ISSUE TITLE
Create new item with "Enter" key when there is no perfect match in any option

### ISSUE THREAD

**Issue by sfmendes91** [brianreavis/selectize.js#1990]
Hello,

Is there a way in selectize package for changing the behavior when "Enter" is selected, to create a new item instead of selecting the option with some score (searching for match purpose) value.

So what I mean is, following the image bellow:
When I search for the value "1231" there is no perfect matching, in this case when I select "Enter" key I want to create a new item (1), but instead the "Enter" is selecting the option "123123" (2) because there are some kind of score value.

Actual result:
![image](https://user-images.githubusercontent.com/5550353/227191757-019b5c5b-85cd-4f04-928d-c50a28cef483.png)

Expected result:
Is there a way for changing this? To when user search by a value, to show all available options but if there are no PERFECT match and user selects "Enter" key to add a new item instead of selecting the option with some kind of match?

**Comment by herrniffler** [comment]
Yes, i totally agree. This i also have this issue.
