### ISSUE TITLE
Autocomplete doesn't offer words starting with čžř

### ISSUE THREAD

**Issue by obikenoby** [brianreavis/selectize.js#1993]
Autocomplete doesn't offer words starting with čžř, it worked in the version 0.12 and stopped working after upgrading to last version.

Steps to reproduce:

1. click to the input field
2. start typing any of czech characters [čžř]
3. words are not selected when the word starts with characters above

Expected result: autocompete offers for example word žloutek

Actual result: nothing offered by autocomplete

[you can add explanations here of the context/what you were trying to
do, and if you have findings about what the cause might be]

**Comment by azabolo** [comment]
Try option `respect_word_boundaries`


```
$('#target').selectize({  
  respect_word_boundaries: false,  
})
```

**Comment by obikenoby** [comment]
Thank you, it helps.
