### ISSUE TITLE
Multiple select dropdowns overlap

### ISSUE THREAD

**Issue by kkstoklund** [brianreavis/selectize.js#2001]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

Steps to reproduce:

1. Open the jsfiddle https://jsfiddle.net/kkstoklund/z9pd04xq/3/
2. Select the first dropdown
3. Use the keyboard tab key to go the the next dropdown

Expected result:
When focusing on the next dropdown, the initial one should lose focus and close.

Actual result:
The dropdown doesn't blur when selecting the next dropdown.

**Comment by alanchiminplantae** [comment]
Workaround:

```
Selectize.prototype._setValue = Selectize.prototype.setValue;
Selectize.prototype._onChange = Selectize.prototype.onChange;
Selectize.prototype._open = Selectize.prototype.open;

$.extend(Selectize.prototype, {
    setValue: function (value, silent) {
        Selectize.prototype._setValue.apply(this, arguments);

        if (this.settings.mode === 'single')
            this.blur();
    },

    onChange: function() {
        Selectize.prototype._onChange.apply(this, arguments);

        if (this.settings.mode === 'single')
            this.blur();
    },

    open: function() {
        Selectize.prototype._open.apply(this, arguments);

        $('select')
            .not(this.$input)
            .toArray()
            .forEach(select => select.selectize?.blur());
    },
});
```

**Comment by rrlapointe** [comment]
This issue is still valid.

**Comment by Gildedter** [comment]
This still persist, the workaround still works too.
