### ISSUE TITLE
Typescript declaration file is not included in package on install

### ISSUE THREAD

**Issue by dcavanagh** [brianreavis/selectize.js#2002]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

[replace me with a short description of issue]

Steps to reproduce:

1. npm install @selectize/selectize
2. ls node_modules/@selectize/selectize

Expected result:
LICENSE      README.md    dist         index.d.ts   package.json

Actual result:
LICENSE      README.md    dist         package.json

index.d.ts is missing from the directory and is needed when using typescript

**Comment by cpsievert** [comment]
I would like to see this problem fixed

**Comment by dvg-p4** [comment]
This is still an issue, and seems relatively straightforward to fix?

**Comment by dvg-p4** [comment]
Currently the lack of a typescript definition file can be worked around by using the definition file from https://github.com/DefinitelyTyped/DefinitelyTyped, which appears to be more up-to-date (though [not completely](https://github.com/DefinitelyTyped/DefinitelyTyped/issues?q=is%3Aissue+is%3Aopen+selectize)).

**Comment by dvg-p4** [comment]
c.f. https://github.com/selectize/selectize.js/issues/2145 -- note that the current file's signatures are significantly out-of-date.
