### ISSUE TITLE
Search doesn't work for items with cyrillic labels / values

### ISSUE THREAD

**Issue by torasko** [brianreavis/selectize.js#2005]
Demo: [https://jsfiddle.net/nbod8k09/](https://jsfiddle.net/nbod8k09/)

Steps to reproduce:

1. Open demo.
2. Click on a selectized item with "select persons placeholder".
3. Search for "Один" or "Два".

**Comment by obikenoby** [comment]
Try option **respect_word_boundaries**

```
$('#target').selectize({  
  respect_word_boundaries: false,  
})

```
