### ISSUE TITLE
Sass compilation errors with Bootstrap 5.3.1

### ISSUE THREAD

**Issue by cpsievert** [brianreavis/selectize.js#2029]
Bootstrap 5.3.1 moves more colors from Sass to CSS variables, which causes a couple compilation errors. Specifically,

https://github.com/selectize/selectize.js/blob/e3f2e0b4aa251375bc21b5fcd8ca7d374a921f08/src/scss/selectize.bootstrap5.scss#L29-L33

Doesn't work anymore since `$input-bg`'s value now contains a CSS variable...

```
Error: argument `$color2` of `mix($color1, $color2, $weight: 50)` must be a color
        on line 26:36 of inst/www/shared/selectize/scss/selectize.bootstrap5.scss, in function `mix`
        from line 26:36 of inst/www/shared/selectize/scss/selectize.bootstrap5.scss
        from line 21:9 of stdin
>> $select-color-dropdown-border-top: mix(
```

For similar reasons, this code:

https://github.com/selectize/selectize.js/blob/e3f2e0b4aa251375bc21b5fcd8ca7d374a921f08/src/plugins/dropdown_header/plugin.scss#L7

Results in

```
Error: argument `$color1` of `mix($color1, $color2, $weight: 50)` must be a color
        on line 7:17 of inst/www/shared/selectize/plugins/dropdown_header/plugin.scss, in function `mix`
        from line 7:17 of inst/www/shared/selectize/plugins/dropdown_header/plugin.scss
        from line 77:9 of inst/www/shared/selectize/scss/selectize.scss
        from line 53:9 of inst/www/shared/selectize/scss/selectize.bootstrap5.scss
        from line 21:9 of stdin
>>     background: mix($select-color-dropdown, $select-color-border, 85);
```

**Comment by cpsievert** [comment]
Commenting to keep open

**Comment by ejn** [comment]
This appears to still be a problem - trying to update boostrap to 5.3.3 doesn't work. @cpsievert appears to have a fix, but doesn't seem to have been merged/released?

**Comment by ejn** [comment]
Any progress on this? It looks like the fix could be very simple (see https://github.com/cpsievert/selectize.js/pull/2/files)
