### ISSUE TITLE
Documentation for `selectOnTab`'s default is out of date 

### ISSUE THREAD

**Issue by cpsievert** [brianreavis/selectize.js#2067]
The docs state that `selectOnTab` defaults to `false`, when in fact, it defaults to `true`. 

https://github.com/selectize/selectize.js/blob/e3f2e0b4aa251375bc21b5fcd8ca7d374a921f08/docs/docs/usage.mdx#L86

https://github.com/selectize/selectize.js/blob/e3f2e0b4aa251375bc21b5fcd8ca7d374a921f08/src/defaults.js#L21

Note that the default was changed here https://github.com/selectize/selectize.js/issues/945, but as other users have [brought up](https://github.com/selectize/selectize.js/issues/1243), `selectOnTab: true` isn't a great experience for keyboard-only users trying to navigate through a larger site (I'd be in support of reverting the default back to `false`).

**Comment by databyte** [comment]
Given the context of the feature is more akin to a dialog box than a simple select input dropdown, the Escape key works fine. When used as a single-select dropdown, it functions as a regular HTML-based dropdown where Tab selects the item and moves to the next object on page.

Changing it now would be a major change given how many years old that adjustment was.

The decision wouldn't be up to just me.
