### ISSUE TITLE
Selectize with Laravel full text search not working

### ISSUE THREAD

**Issue by vaasi88** [brianreavis/selectize.js#2084]
All functionality working fine except any character search in the selectize dropdown.

![image](https://github.com/selectize/selectize.js/assets/160050196/6f7cfc42-9181-4ed8-9c88-9911722546a4)

the search is working fine with the starting letters, but not with in the middle order characters.
So typing "Ba" is working and finding the words correctly.
![image](https://github.com/selectize/selectize.js/assets/160050196/3b2edeb7-81b2-4103-a200-e0d0fdf23ea4)

But searching "an" is not working.
![image](https://github.com/selectize/selectize.js/assets/160050196/1af4e860-2a95-48cb-b70c-fb0e8e78a504)

My initialization part in app.js is,

`import Selectize from '@selectize/selectize'`;
`window.Selectize = Selectize;`

What could be the problem.?  i installed this selectize using npm package.
`npm i @selectize/selectize`

Thanks in advance!
- by vaasi88

**Comment by 4C-DSolomon** [comment]
I ran into the same issue upgrading, probably the same root cause: `respect_word_boundaries` is a new configuration option that was added. It defaults to `true`. Try setting that to `false` instead.
