### ISSUE TITLE
Hovered option is automatically selected on blur

### ISSUE THREAD

**Issue by brandonkelly** [brianreavis/selectize.js#2085]
> I did:
>
> * [x] Search for if my issue has already been submitted
> * [x] Make sure I'm reporting something precise that needs to be fixed
> * [x] Give my issue a descriptive and concise title
> * [x] Create a *minimal* working example on JsFiddle or Codepen (or gave a link to a demo on the Selectize docs)
> * [x] Indicate *precise* steps to reproduce in *numbers* and the result, like below

---

### Description

When you hover over an item and then press <kbd>Tab</kbd> to move focus to another input, the item that was being hovered over is automatically selected.

### Steps to reproduce

1. <kbd>Tab</kbd> into a Selectize input (such as the one [here](https://selectize.dev/docs/demos/dynamic-option-groups)) to focus it.
2. Hover over an item – but **don’t** mousedown or press <kbd>Return</kbd>, etc.
3. <kbd>Tab</kbd> out of the Selectize input to blur it.

### Expected result

No change to the Selectize input is made, since no explicit action was taken suggesting a new value should be selected.

### Actual result

The hovered item is automatically selected.

### Video demonstration

Here’s a video demonstration using the [Dynamic Option Groups](https://selectize.dev/docs/demos/dynamic-option-groups) example input. Note the position of the cursor the first two times the Selectize field is focused (up above the input) versus the third time (below the input, where the menu will expand to).

https://github.com/selectize/selectize.js/assets/47792/36ceb900-95c9-4bcf-b7c7-25f86e0c07e7

**Comment by winzig** [comment]
Set `selectOnTab` to `false`.

**Comment by brandonkelly** [comment]
Aha, thank you @winzig! Seems like that should probably be the default behavior…

**Comment by winzig** [comment]
Theoretically it is: https://selectize.dev/docs/usage

But I haven't tested that in a while on the standard distribution.
